### ISSUE TITLE
DOS image error

### ISSUE THREAD

**Issue by Bowser35** [lilbud/es-theme-switch-dark#2]
The image for the DOS theme on the home screen just shows the letters pc, I tried uninstalling and reinstalling the theme and still no luck
(https://user-images.githubusercontent.com/41450754/42967822-10373416-8b67-11e8-84cc-e7f6a64f5ec6.jpg)

**Comment by lilbud** [comment]
The image is in fact in the theme, it is named "dos.png" I thought that was the naming. I'll rename it to PC.png for now. 

I coulda sworn that I had a image for PC, turns out it was just named wrong.

**Comment by lilbud** [comment]
There, the file is renamed properly. Update from the theme downloader.

I was working on an update to this theme recently, this was the first time I actually looked through my old code for this.

**Comment by Bowser35** [comment]
Cool looks like that did the trick, thanks!
