### ISSUE TITLE
Permission to use theme images

### ISSUE THREAD

**Issue by s4ilence** [lilbud/es-theme-switch-dark#3]
Hi @lilbud  I would like to use your theme(s) and images on devices running Retrofw.
These devices use a low power ingenic mips processor and are not capable of running emulationstation. Jack wrote a little menu that mimics the look of es written in python pymenu and would like to use use themes, but could not find a license.

best regards,
Sailence

**Comment by lilbud** [comment]
Sure, but this version hasn't been updated since mid 2017. I moved over to a new repository that combines the light and dark mode into one theme (makes updates easier.)
https://github.com/lilbud/es-theme-switch

Just make sure you credit me when you port it over.

**Comment by Apaczer** [comment]
Sorry for asking here, but @s4ilence are you creator of Grid & NsDark themes for GMenu2X? I wanted also to ask for permission to modify/distribute your work, could you contact me at apaczer.git@gmail.com 🙏 ?

**Comment by s4ilence** [comment]
> Sorry for asking here, but @s4ilence are you creator of Grid & NsDark themes for GMenu2X? I wanted also to ask for permission to modify/distribute your work, could you contact me at [apaczer.git@gmail.com](mailto:apaczer.git@gmail.com) 🙏 ?

Hi sure! no problem 🔥

**Comment by Apaczer** [comment]
Cool! I would like to provide it under genereal GPLv2 License, is it ok? We
have set your skin as default for MiyooCFW, really appreciate what u have
done.

**Comment by s4ilence** [comment]
> Cool! I would like to provide it under genereal GPLv2 License, is it ok? We have set your skin as default for MiyooCFW, really appreciate what u have done.

Yup go on you have my full permission on that skin, Thanks for appreciation! happy to help 😄🔥
