### ISSUE TITLE
Wii U support?

### ISSUE THREAD

**Issue by roythearsonist** [lilbud/es-theme-switch-dark#4]
I know it's kinda dead but I like it. Anyway, does anyone know how to run wii u games with this?

**Comment by lilbud** [comment]
First off: you should switch over to the new version I released a bit ago (https://github.com/lilbud/es-theme-switch). This version is extremely out of date. 

Second: The only way to do that would be to use Cemu, which is PC only. I believe there is a version of ES for windows but I don't know atm.

**Comment by roythearsonist** [comment]
Fair enough, have a nice day.
